=== wanggit/qcadoo-copy-framework/qcadoo-model/src/main/resources/com/qcadoo/model/common/model.xsd
<?xml version="1.0"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:include schemaLocation="http://schema.qcadoo.org/common/plugin.xsd" />

	<xs:group name="hooksType">
		<xs:choice>
			<xs:element name="validatesWith" type="hookType" />
			<xs:element name="onSave" type="hookType" />
			<xs:element name="onUpdate" type="hookType" />
			<xs:element name="onCreate" type="hookType" />
			<xs:element name="onCopy" type="hookType" />
			<xs:element name="onView" type="hookType" />
			<xs:element name="onDelete" type="hookType" />
		</xs:choice>
	</xs:group>

	<xs:group name="fieldsType">
		<xs:choice>
			<xs:element name="integer" type="integerFieldType" />
			<xs:element name="string" type="stringFieldType" />
			<xs:element name="text" type="characterFieldType" />
			<xs:element name="decimal" type="decimalFieldType" />
			<xs:element name="datetime" type="dateFieldType" />
			<xs:element name="date" type="dateFieldType" />
			<xs:element name="boolean" type="primitiveValueFieldType" />
			<xs:element name="belongsTo" type="belongsToFieldType" />
			<xs:element name="hasMany" type="hasManyFieldType" />
			<xs:element name="manyToMany" type="manyToManyFieldType" />
			<xs:element name="tree" type="treeFieldType" />
			<xs:element name="enum" type="enumFieldType" />
			<xs:element name="dictionary" type="dictionaryFieldType" />
			<xs:element name="password" type="characterFieldType" />
			<xs:element name="priority" type="priorityFieldType" minOccurs="0" maxOccurs="1" />
			<xs:element name="file" type="fieldType" />
		</xs:choice>
	</xs:group>

	<xs:complexType name="identifierExpressionType">
		<xs:attribute name="expression" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="masterModelType">
		<xs:attribute name="model" type="identifier" use="required" />
		<xs:attribute name="plugin" type="identifier" use="required" />
	</xs:complexType>

	<xs:complexType name="validatesType">
		<xs:attribute name="message" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="validatesLengthType">
		<xs:complexContent>
			<xs:extension base="validatesType">
				<xs:attribute name="min" type="xs:integer" />
				<xs:attribute name="is" type="xs:integer" />
				<xs:attribute name="max" type="xs:integer" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="validatesRangeType">
		<xs:complexContent>
			<xs:extension base="validatesType">
				<xs:attribute name="from" type="xs:string" />
				<xs:attribute name="to" type="xs:string" />
				<xs:attribute name="exclusively" type="xs:boolean" default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="validatesRegexType">
		<xs:complexContent>
			<xs:extension base="validatesType">
				<xs:attribute name="pattern" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="hookType">
		<xs:attribute name="class" type="classIdentifier" use="required" />
		<xs:attribute name="method" type="identifier" use="required" />
	</xs:complexType>

	<xs:complexType name="fieldType">
		<xs:attribute name="name" type="identifier" use="required" />
		<xs:attribute name="readonly" type="xs:boolean" default="false" />
		<xs:attribute name="persistent" type="xs:boolean" default="true" />
		<xs:attribute name="required" type="xs:boolean" default="false" />
	</xs:complexType>

	<xs:complexType name="primitiveValueFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="unique" type="xs:boolean" default="false" />
				<xs:attribute name="default" type="xs:string" />
				<xs:attribute name="copyable" type="xs:boolean" default="true" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="dateFieldType">
		<xs:complexContent>
			<xs:extension base="primitiveValueFieldType">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="validatesWith" type="hookType" />
					<xs:element name="validatesRegex" type="validatesRegexType" />

					<xs:element name="validatesRange" type="validatesRangeType" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="integerFieldType">
		<xs:complexContent>
			<xs:extension base="primitiveValueFieldType">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="validatesWith" type="hookType" />
					<xs:element name="validatesRegex" type="validatesRegexType" />

					<xs:element name="validatesUnscaledValue" type="validatesLengthType" />
					<xs:element name="validatesRange" type="validatesRangeType" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="decimalFieldType">
		<xs:complexContent>
			<xs:extension base="primitiveValueFieldType">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="validatesWith" type="hookType" />
					<xs:element name="validatesRegex" type="validatesRegexType" />

					<xs:element name="validatesUnscaledValue" type="validatesLengthType" />
					<xs:element name="validatesScale" type="validatesLengthType" />
					<xs:element name="validatesRange" type="validatesRangeType" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="characterFieldType">
		<xs:complexContent>
			<xs:extension base="primitiveValueFieldType">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="validatesWith" type="hookType" />
					<xs:element name="validatesRegex" type="validatesRegexType" />

					<xs:element name="validatesLength" type="validatesLengthType" />
					<xs:element name="validatesRange" type="validatesRangeType" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="stringFieldType">
		<xs:complexContent>
			<xs:extension base="characterFieldType">
				<xs:attribute name="expression" type="xs:string" use="optional" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="belongsToFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="validatesWith" type="hookType" />
				</xs:choice>
				<xs:attribute name="model" type="identifier" use="required" />
				<xs:attribute name="plugin" type="identifier" />
				<xs:attribute name="lazy" type="xs:boolean" default="true" />
				<xs:attribute name="unique" type="xs:boolean" default="false" />
				<xs:attribute name="copyable" type="xs:boolean" default="true" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="collectionValueFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="model" type="identifier" use="required" />
				<xs:attribute name="plugin" type="identifier" />
				<xs:attribute name="joinField" type="identifier"
				              use="required" />
				<xs:attribute name="cascade" type="cascadeType" default="nullify"
				              use="optional" />
				<xs:attribute name="copyable" type="xs:boolean" default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="hasManyFieldType">
		<xs:complexContent>
			<xs:extension base="collectionValueFieldType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="manyToManyFieldType">
		<xs:complexContent>
			<xs:extension base="collectionValueFieldType">
				<xs:attribute name="lazy" type="xs:boolean" default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="treeFieldType">
		<xs:complexContent>
			<xs:extension base="collectionValueFieldType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="dictionaryFieldType">
		<xs:complexContent>
			<xs:extension base="characterFieldType">
				<xs:attribute name="dictionary" type="identifier"
				              use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="enumFieldType">
		<xs:complexContent>
			<xs:extension base="primitiveValueFieldType">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="validatesWith" type="hookType" />
				</xs:choice>
				<xs:attribute name="values" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[a-zA-Z0-9]*(,[a-zA-Z0-9]*)*" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="priorityFieldType">
		<xs:attribute name="name" type="identifier" use="required" />
		<xs:attribute name="scope" type="identifier" use="optional" />
	</xs:complexType>

	<xs:simpleType name="cascadeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="delete" />
			<xs:enumeration value="nullify" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="deletableType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="false" />
			<xs:enumeration value="true" />
			<xs:enumeration value="soft" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== wanggit/qcadoo-copy-framework/qcadoo-model/src/test/resources/model/full/firstEntity.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.2.0

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model plugin="full" name="firstEntity" insertable="false"
	activable="true" auditable="true" deletable="false"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
	xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
	<fields>
		<integer name="fieldInteger" required="true" unique="true" copyable="false">
			<validatesWith class="com.qcadoo.model.CustomHook"
				method="validateField" />
			<validatesLength min="1" max="3" />
			<validatesUnscaledValue min="2" max="4" />
			<validatesRange from="18" exclusively="true" />
		</integer>
		<string name="fieldString" default="ala" required="true" unique="false">
			<validatesLength is="2" />
			<validatesRange from="daap" to="dzzp" />
			<validatesRegex pattern="d??p" />
		</string>
		<string name="fieldStringWithoutValidators" />
		<text name="fieldText" readonly="true" />
		<string name="fieldStringNotPersistent" persistent="false" />
		<string name="fieldStringWithExpression" expression="#fString" />
		<decimal name="fieldDecimal">
			<validatesScale min="2" max="4" />
			<validatesUnscaledValue is="2" />
		</decimal>
		<decimal name="fieldDecimalOnlyWithScale">
			<validatesScale min="2" max="4" />
		</decimal>
		<decimal name="fieldDecimalWithoutValidators" />
		<datetime name="fieldDatetime" required="false" />
		<date name="fieldDate" />
		<boolean name="fieldBoolean" />
		<belongsTo name="fieldThirdEntity" model="thirdEntity" lazy="false" />
		<belongsTo name="fieldSecondEntity" plugin="other" model="secondEntity"
			lazy="false" />
		<belongsTo name="fieldSecondEntity2" plugin="other" model="secondEntity"
			lazy="true" required="true" />
		<tree name="fieldTree" model="secondEntity" cascade="delete"
			joinField="fieldFirstEntity" />
		<hasMany name="fieldHasMany" model="thirdEntity" cascade="nullify"
			joinField="fieldFirstEntity" />
		<manyToMany name="fieldManyToMany" model="thirdEntity"
			cascade="delete" joinField="fieldManyToMany" />
		<dictionary name="fieldDictionary" dictionary="categories" />
		<dictionary name="fieldOtherDictionary" dictionary="categories" />
		<enum name="fieldEnum" values="one,two,three" />
		<password name="fieldPassword" />
		<priority name="fieldPriority" scope="fieldInteger" />
	</fields>
	<hooks>
		<validatesWith class="com.qcadoo.model.CustomHook"
			method="validate" />
		<onSave class="com.qcadoo.model.CustomHook" method="hook" />
		<onUpdate class="com.qcadoo.model.CustomHook" method="updateHook" />
		<onCreate class="com.qcadoo.model.CustomHook" method="createHook" />
		<onCopy class="com.qcadoo.model.CustomHook" method="copyHook" />
		<onDelete class="com.qcadoo.model.CustomHook" method="deleteHook" />
	</hooks>
	<identifier expression="#fieldString" />
</model>

=== wanggit/qcadoo-copy-framework/qcadoo-model/src/test/resources/products/model/part.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.2.0

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="part" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
	xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
	<fields>
		<string name="name" required="true" />
		<belongsTo name="product" model="product" required="false"
			lazy="false" />
		<belongsTo name="component" model="component" required="false"
			lazy="false" />
		<manyToMany name="products" model="product" plugin="products" joinField="partsManyToMany" cascade="nullify" />
		<decimal name="price" />
		<integer name="weight" />
		<text name="description" />
		<text name="longDescription">
			<validatesLength max="4096" />
		</text>
		<password name="discountCode" />
		<password name="longDiscountCode">
			<validatesLength max="512"/>
		</password>
		<boolean name="deletionIsProhibited" />
		
 		<hasMany name="factories" joinField="parentPart" model="factory" cascade="delete" />
	</fields>
	<hooks>
		<onDelete class="com.qcadoo.model.integration.VerifyHooks" method="onDeleteUsingBooleanField2" />
	</hooks>
</model>

=== wanggit/qcadoo-copy-framework/qcadoo-model/src/test/resources/products/model/product.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.2.0

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="product" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
	xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
	<fields>
		<string name="number" required="true" unique="true" />
		<string name="name" required="true">
			<validatesLength max="512" />
		</string>
		<string name="changeableName" />
		<enum name="enum" values="one,two" />
		<integer name="quantity">
			<validatesRange from="0" exclusively="true" />
		</integer>
		<dictionary name="category" dictionary="categories" />
		<hasMany name="components" model="component" joinField="product"
			cascade="delete" />
		<hasMany name="parts" model="part" joinField="product"
			cascade="delete" />
		<manyToMany name="partsManyToMany" model="part" plugin="products" joinField="products" copyable="true" cascade="delete" />
		<manyToMany name="lazyManyToMany" model="versionableEntity" plugin="products" joinField="products" copyable="true" cascade="delete" lazy="true"/>
		<string name="readOnly" readonly="true" />
	</fields>
	<hooks>
		<onCopy class="com.qcadoo.model.integration.VerifyHooks" method="onCopy"/>
		<onCreate class="com.qcadoo.model.integration.VerifyHooks" method="onCreate"/>
		<onSave class="com.qcadoo.model.integration.VerifyHooks" method="onSave"/>
		<onUpdate class="com.qcadoo.model.integration.VerifyHooks" method="onUpdate"/>
		
		<onCopy class="com.qcadoo.model.integration.VerifyHooks" method="changeReadOnlyFieldOnCopy"/>
		<onCreate class="com.qcadoo.model.integration.VerifyHooks" method="changeReadOnlyFieldOnCreate"/>
		<onSave class="com.qcadoo.model.integration.VerifyHooks" method="changeReadOnlyFieldOnSave"/>
		<onUpdate class="com.qcadoo.model.integration.VerifyHooks" method="changeReadOnlyFieldOnUpdate"/>
	</hooks>
</model>

=== wanggit/qcadoo-copy-framework/qcadoo-security/src/main/resources/qcadooSecurity/model/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="user" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://schema.qcadoo.org/model"
	xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">

	<fields>
		<string name="userName" required="true" unique="true">
			<validatesRegex pattern="^[a-zA-Z0-9\\.@_-]+$"
				message="qcadooSecurity.validate.global.error.loginIllegalCharacters" />
		</string>
		<string name="email">
			<validatesWith class="com.qcadoo.security.internal.validators.EmailValidationService" method="checkEmail"/>
		</string>
		<string name="firstName" required="true" />
		<string name="lastName" required="true" />
		<boolean name="enabled" default="true" />
		<string name="description">
			<validatesLength max="255" />
		</string>
		<password name="password" /><!-- TODO validatesPresenceOnCreate -->
		<password name="passwordConfirmation" persistent="false" /><!-- 
			TODO validatesPresenceOnCreate -->
		<password name="oldPassword" persistent="false" />
		<string name="viewIdentifier" persistent="false" />
		<datetime name="lastActivity" />
		<datetime name="groupChangeDate" />
		<string name="ipAddress" />
		<belongsTo name="group" model="group" required="true"/>
		<hasMany name="passwordResetTokens" model="passwordResetToken" joinField="user" cascade="delete"/>
		<datetime name="pswdLastChanged"/>
		<boolean name="afterFirstPswdChange" default="false"/>
		<boolean name="isBlocked" default="false"/>
	</fields>

	<hooks>
		<validatesWith class="com.qcadoo.security.internal.validators.PasswordValidationService"
			method="checkPassword" />
		<validatesWith class="com.qcadoo.security.internal.validators.UserRoleValidationService"
			method="checkUserCreatingSuperadmin" />
		<validatesWith class="com.qcadoo.security.internal.hooks.UserModelHooks"
		               method="validateGroupChangeDate" />

        <onCreate class="com.qcadoo.security.internal.hooks.UserModelHooks"
            method="setDefaultNames" />

		<onDelete class="com.qcadoo.security.internal.hooks.UserModelHooks" 
			method="preventSelfDeletion" />

		<onSave class="com.qcadoo.security.internal.hooks.UserModelHooks"
				  method="checkIfEmailNotificationShouldBeSent" />
		<onSave class="com.qcadoo.security.internal.hooks.UserModelHooks"
				method="updatePswdLastChanged" />
	</hooks>

	<identifier expression="#userName" />
</model>
