=== wanggit/qcadoo-copy-framework/qcadoo-view/src/main/resources/com/qcadoo/view/view.xsd
<?xml version="1.0"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://schema.qcadoo.org/view" xmlns="http://schema.qcadoo.org/view">

    <xs:include schemaLocation="common/view.xsd"/>

    <xs:element name="view">
        <xs:complexType>
            <xs:sequence>
                <xs:any minOccurs="1" maxOccurs="unbounded" processContents="skip"/>
            </xs:sequence>
            <xs:attribute name="name" type="identifierType" use="required"/>
            <xs:attribute name="modelPlugin" type="identifierType" use="optional"/>
            <xs:attribute name="modelName" type="identifierType" use="optional"/>
            <xs:attribute name="menuAccessible" type="xs:boolean" default="false"/>
            <xs:attribute name="defaultAuthorizationRole" type="xs:string" use="optional"/>
            <xs:attribute name="windowWidth" type="xs:positiveInteger" use="optional"/>
            <xs:attribute name="windowHeight" type="xs:positiveInteger" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ribbonType">
        <xs:sequence>
            <xs:element name="group" type="ribbonGroupType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ribbonGroupType">
        <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="bigButton" type="ribbonActionType"/>
                <xs:element name="bigButtons" type="ribbonComboType"/>
                <xs:element name="smallButton" type="ribbonActionType"/>
                <xs:element name="smallButtons" type="ribbonComboType"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="identifierType" use="required"/>
        <xs:attribute name="defaultAuthorizationRole" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="ribbonComboType">
        <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="bigButton" type="ribbonActionType"/>
                <xs:element name="smallButton" type="ribbonActionType"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="identifierType" use="required"/>
        <xs:attribute name="icon" type="xs:string"/>
        <xs:attribute name="action" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="ribbonActionType">
        <xs:attribute name="name" type="identifierType" use="required"/>
        <xs:attribute name="icon" type="xs:string"/>
        <xs:attribute name="action" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="componentType">
        <xs:sequence>
            <xs:element name="ribbon" type="ribbonType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="component" type="componentType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="option" type="optionType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="listener" type="listenerType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="rowStyleResolver" type="hookType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="criteriaModifier" type="hookType" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="type" type="identifierType" use="required"/>
        <xs:attribute name="name" type="identifierType" use="required"/>
        <xs:attribute name="reference" type="identifierType" use="optional"/>
        <xs:attribute name="field" type="xs:string"/>
        <xs:attribute name="source" type="xs:string"/>
        <xs:attribute name="defaultEnabled" type="enabledAttribute"/>
        <xs:attribute name="defaultVisible" type="xs:boolean"/>
        <xs:attribute name="hasDescription" type="xs:boolean" default="false"/>
        <xs:attribute name="persistent" type="xs:boolean" default="true"/>
    </xs:complexType>

    <xs:complexType name="optionType">
        <xs:attribute name="type" type="identifierType" use="required"/>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="fields" type="xs:string"/>
        <xs:attribute name="expression" type="xs:string"/>
        <xs:attribute name="aggregation" type="xs:string"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="width" type="xs:string"/>
        <xs:attribute name="link" type="xs:string"/>
        <xs:attribute name="hidden" type="xs:boolean"/>
        <xs:anyAttribute/>
    </xs:complexType>

</xs:schema>

=== wanggit/qcadoo-copy-framework/qcadoo-plugins-dictionary-management/src/main/resources/qcadooDictionaries/view/dictionaryDetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view"
	  xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd" name="dictionaryDetails"
	  modelPlugin="qcadooModel" modelName="dictionary" defaultAuthorizationRole="ROLE_DICTIONARY_VIEW">

	<component type="window" name="window" reference="window">

		<ribbon>
			<template name="standardFormTemplate" includeItems="navigation.back"/>
			<template name="standardGridTemplate" excludeItems="actions.delete,actions.copy"/>
		</ribbon>

		<component type="form" reference="form" name="dictionary">
			<option type="header" value="true"/>
			<option type="expression" value="'@' + #pluginIdentifier + '.' + #name + '.dictionary'"/>
		</component>

		<component type="grid" name="dictionaryItems" reference="grid"
				   source="#{form}.dictionaryItems">
			<script>
				<![CDATA[
					var activateButton = #{window}.getRibbonItem("states.activate");
					var deactivateButton = #{window}.getRibbonItem("states.deactivate");

					var listener = {
						onChange: function(selectedEntitiesArray) {
							if (!selectedEntitiesArray || selectedEntitiesArray.length == 0) {
								activateButton.disable();
								deactivateButton.disable();
							} else {
								var hasExternal = false;
								var hasTechnicalCode = false;

								for (var i in selectedEntitiesArray) {
									if (selectedEntitiesArray[i].fields.externalNumber != '' && selectedEntitiesArray[i].fields.externalNumber != undefined) {
										hasExternal = true;
										break;	
									}
									if (selectedEntitiesArray[i].fields.technicalCode != '' && selectedEntitiesArray[i].fields.technicalCode != undefined) {
										hasTechnicalCode = true;
										break;	
									}
								}
								if (hasExternal) {
									activateButton.disable("#{translate(qcadooDictionaries.dictionaryItems.ribbon.message.someDictionaryItemIsExternal)}");
									deactivateButton.disable("#{translate(qcadooDictionaries.dictionaryItems.ribbon.message.someDictionaryItemIsExternal)}");
									return;
								} else {
									activateButton.enable();
									deactivateButton.enable();
								}
								if (hasTechnicalCode) {
									activateButton.disable();
									deactivateButton.disable();
								} else {
									activateButton.enable();
									deactivateButton.enable();
								}
							}

						}
					}
					this.addOnChangeListener(listener);
				]]>
			</script>

			<option type="column" name="name" fields="name" link="true"
					width="50"/>
			<option type="column" name="description" fields="description"
					width="100"/>
			<option type="column" name="priority" fields="priority"
					width="50"/>
			<option type="column" name="externalNumber" fields="externalNumber" hidden="true"/>
			<option type="column" name="technicalCode" fields="technicalCode" hidden="true"/>

			<option type="order" column="name" direction="asc"/>

			<option type="searchable" value="name,description,priority"/>
			<option type="orderable" value="name,description,priority"/>

			<option type="correspondingView" value="qcadooDictionaries/dictionaryItemDetails"/>
			<option type="correspondingComponent" value="form"/>

			<option type="paginable" value="true"/>

			<option type="deletable" value="false"/>
			<option type="creatable" value="false"/>

			<option type="multiselect" value="true"/>
			<option type="fullscreen" value="true"/>
			<option type="fixedHeight" value="true"/>

			<option type="height" value="250"/>
		</component>
	</component>

</view>

=== wanggit/qcadoo-copy-framework/qcadoo-plugins-custom-translation-management/src/main/resources/qcadooCustomTranslations/view/customTranslationsList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view" 
	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
	name="customTranslationsList"
	modelPlugin="qcadooCustomTranslation"
	modelName="customTranslation"
	menuAccessible="true"
	defaultAuthorizationRole="ROLE_ADMIN">
	
	<component type="window" name="window">
		<ribbon>
			<template name="standardGridTemplate" excludeGroups="actions" />
			<group name="clean">
				<bigButton name="cleanCustomTranslations" icon="genealogyIcon24.png" action="#{grid}.fireEvent(cleanCustomTranslations);"
					state="enabled" />
			</group>
			<group name="replace">
				<bigButton name="replaceCustomTranslations" icon="genealogyIcon24.png" action="#{grid}.fireEvent(replaceCustomTranslations);" 
					state="enabled" />
			</group>
		</ribbon>
			
		<component type="gridLayout" name="gridLayout" columns="3"
			rows="2" hasBorders="false">
			<layoutElement column="1" row="1">
				<component type="form" name="localeForm" reference="localeForm">
					<component type="select" name="locale" field="locale" reference="locale">
						<listener
							event="onSelectedEntityChange" 
							class="com.qcadoo.plugins.customTranslations.internal.hooks.CustomTranslationsListViewHooks"
							method="addDiscriminatorRestrictionToGrid" />
					</component>
				</component>
			</layoutElement>
			<layoutElement column="1" row="2" width="3">
				<component type="grid" name="customTranslationsGrid" reference="grid">
					<option type="column" name="pluginName" fields="pluginName" link="true" />
					<option type="column" name="key" fields="key" link="true" />
					<option type="column" name="propertiesTranslation" fields="propertiesTranslation" link="true" />
					<option type="column" name="active" fields="active" />
					<option type="column" name="customTranslation" fields="customTranslation" link="true" />

					<option type="searchable" value="pluginIdentifier,key,active,propertiesTranslation,customTranslation,locale" />
					<option type="orderable" value="pluginIdentifier,key,active,propertiesTranslation,customTranslation,locale" />
					
					<option type="order" column="pluginIdentifier" direction="asc" />
					
					<option type="correspondingView" value="qcadooCustomTranslations/customTranslationDetails" />
					<option type="correspondingComponent" value="form" />
					
					<option type="fullscreen" value="true" />
					<option type="multiselect" value="true" />
					<option type="creatable" value="false" />
					<option type="deletable" value="false" />
		
					<listener event="cleanCustomTranslations" class="com.qcadoo.plugins.customTranslations.internal.listeners.CustomTranslationsListListeners" 
						method="cleanCustomTranslations" />
					<listener event="replaceCustomTranslations" class="com.qcadoo.plugins.customTranslations.internal.listeners.CustomTranslationsListListeners" 
						method="replaceCustomTranslations" />
				</component>
			</layoutElement>
		</component>
		
		<option type="header" value="false" />
	</component>
	
	<hooks>
		<beforeRender
			class="com.qcadoo.plugins.customTranslations.internal.hooks.CustomTranslationsListViewHooks"
			method="setLocaleToDefault" />
		<beforeRender 
			class="com.qcadoo.plugins.customTranslations.internal.hooks.CustomTranslationsListViewHooks"
			method="updateRibbonState" />
		<beforeRender 
			class="com.qcadoo.plugins.customTranslations.internal.hooks.CustomTranslationsListViewHooks"
			method="addDiscriminatorRestrictionToGrid" />
	</hooks>
</view>
