=== wanggit/qcadoo-copy-framework/qcadoo-view/src/main/resources/com/qcadoo/view/view.xsd
<?xml version="1.0"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://schema.qcadoo.org/view" xmlns="http://schema.qcadoo.org/view">

    <xs:include schemaLocation="common/view.xsd"/>

    <xs:element name="view">
        <xs:complexType>
            <xs:sequence>
                <xs:any minOccurs="1" maxOccurs="unbounded" processContents="skip"/>
            </xs:sequence>
            <xs:attribute name="name" type="identifierType" use="required"/>
            <xs:attribute name="modelPlugin" type="identifierType" use="optional"/>
            <xs:attribute name="modelName" type="identifierType" use="optional"/>
            <xs:attribute name="menuAccessible" type="xs:boolean" default="false"/>
            <xs:attribute name="defaultAuthorizationRole" type="xs:string" use="optional"/>
            <xs:attribute name="windowWidth" type="xs:positiveInteger" use="optional"/>
            <xs:attribute name="windowHeight" type="xs:positiveInteger" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ribbonType">
        <xs:sequence>
            <xs:element name="group" type="ribbonGroupType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ribbonGroupType">
        <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="bigButton" type="ribbonActionType"/>
                <xs:element name="bigButtons" type="ribbonComboType"/>
                <xs:element name="smallButton" type="ribbonActionType"/>
                <xs:element name="smallButtons" type="ribbonComboType"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="identifierType" use="required"/>
        <xs:attribute name="defaultAuthorizationRole" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="ribbonComboType">
        <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="bigButton" type="ribbonActionType"/>
                <xs:element name="smallButton" type="ribbonActionType"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="identifierType" use="required"/>
        <xs:attribute name="icon" type="xs:string"/>
        <xs:attribute name="action" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="ribbonActionType">
        <xs:attribute name="name" type="identifierType" use="required"/>
        <xs:attribute name="icon" type="xs:string"/>
        <xs:attribute name="action" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="componentType">
        <xs:sequence>
            <xs:element name="ribbon" type="ribbonType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="component" type="componentType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="option" type="optionType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="listener" type="listenerType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="rowStyleResolver" type="hookType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="criteriaModifier" type="hookType" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="type" type="identifierType" use="required"/>
        <xs:attribute name="name" type="identifierType" use="required"/>
        <xs:attribute name="reference" type="identifierType" use="optional"/>
        <xs:attribute name="field" type="xs:string"/>
        <xs:attribute name="source" type="xs:string"/>
        <xs:attribute name="defaultEnabled" type="enabledAttribute"/>
        <xs:attribute name="defaultVisible" type="xs:boolean"/>
        <xs:attribute name="hasDescription" type="xs:boolean" default="false"/>
        <xs:attribute name="persistent" type="xs:boolean" default="true"/>
    </xs:complexType>

    <xs:complexType name="optionType">
        <xs:attribute name="type" type="identifierType" use="required"/>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="fields" type="xs:string"/>
        <xs:attribute name="expression" type="xs:string"/>
        <xs:attribute name="aggregation" type="xs:string"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="width" type="xs:string"/>
        <xs:attribute name="link" type="xs:string"/>
        <xs:attribute name="hidden" type="xs:boolean"/>
        <xs:anyAttribute/>
    </xs:complexType>

</xs:schema>

=== wanggit/qcadoo-copy-framework/qcadoo-plugins-user-management/src/main/resources/qcadooUsers/view/groupsList.xml
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view"
	  xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd" name="groupsList"
	  modelPlugin="qcadooSecurity" modelName="group" menuAccessible="true" defaultAuthorizationRole="ROLE_GROUPS_VIEW">

	<component type="window" name="window">

		<ribbon>
			<group template="gridNewCopyAndRemoveAction" defaultAuthorizationRole="ROLE_GROUPS_EDIT"/>
			<group name="actions">
				<bigButton name="refresh" icon="updateIcon24.png" state="enabled" action="#{grid}.performRefresh;" accesskey="r" />
			</group>
			<group template="gridGenericExportAction"/>
		</ribbon>

		<component type="grid" name="groups" reference="grid">
			<option type="column" name="name" fields="name" link="true"/>
			<option type="column" name="identifier" fields="identifier" link="true"/>
			<option type="column" name="description" fields="identifier,description"
					expression="(#description == null) ? ((#identifier == null) ? '' : '@qcadooSecurity.group.' + #identifier + '.description') : #description"/>
			<option type="column" name="permissionType" fields="permissionType"/>

			<option type="order" column="name" direction="asc"/>

			<option type="orderable" value="name,identifier,permissionType"/>
			<option type="searchable" value="name,identifier,permissionType"/>

			<option type="correspondingView" value="qcadooUsers/groupDetails"/>
			<option type="correspondingComponent" value="form"/>

			<option type="fullscreen" value="true"/>
			<option type="multiselect" value="true"/>
		</component>

		<option type="fixedHeight" value="true"/>
		<option type="header" value="false"/>
	</component>

</view>

=== wanggit/qcadoo-copy-framework/qcadoo-plugins-dictionary-management/src/main/resources/qcadooDictionaries/view/dictionariesList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view"
	  xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd" name="dictionariesList"
	  modelPlugin="qcadooModel" modelName="dictionary" menuAccessible="true"
	  defaultAuthorizationRole="ROLE_DICTIONARY_VIEW">

	<component type="window" name="window">

		<ribbon>
		</ribbon>

		<component type="grid" name="dictionaries" reference="grid">
			<option type="column" name="label" fields="name" link="true"/>
			<option type="order" column="label" direction="asc"/>
			<option type="paginable" value="true"/>
			<option type="correspondingView" value="qcadooDictionaries/dictionaryDetails"/>
			<option type="correspondingComponent" value="form"/>
			<option type="deletable" value="false"/>
			<option type="creatable" value="false"/>
			<option type="fullscreen" value="true"/>
		</component>

		<option type="fixedHeight" value="true"/>
		<option type="header" value="false"/>
	</component>

	<hooks>
		<beforeRender class="com.qcadoo.plugins.dictionaries.internal.ViewDictionaryService"
					  method="addRestrictionToDictionariesGrid"/>
		<beforeRender class="com.qcadoo.plugins.dictionaries.internal.ViewDictionaryService" method="translateLabel"/>
	</hooks>

</view>

=== wanggit/qcadoo-copy-framework/qcadoo-plugins-user-management/src/main/resources/qcadooUsers/view/rolesList.xml
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view"
	  xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd" name="rolesList"
	  modelPlugin="qcadooSecurity" modelName="role" menuAccessible="true" defaultAuthorizationRole="ROLE_SUPERADMIN">

	<component type="window" name="window">

		<ribbon>
			<template name="standardGridTemplate" excludeItems="actions.copy, actions.delete, actions.new"/>
		</ribbon>

		<component type="grid" name="roles" reference="grid">
			<option type="column" name="identifier" fields="identifier" link="true"/>
			<option type="column" name="description" fields="identifier,description"
					expression="(#description == null) ? '@qcadooSecurity.role.' + #identifier + '.description' : #description"/>

			<option type="order" column="identifier" direction="asc"/>

			<option type="orderable" value="identifier"/>
			<option type="searchable" value="identifier"/>

			<option type="correspondingView" value="qcadooUsers/roleDetails"/>
			<option type="correspondingComponent" value="form"/>

			<option type="fullscreen" value="true"/>
			<option type="multiselect" value="true"/>
		</component>

		<option type="fixedHeight" value="true"/>
		<option type="header" value="false"/>
	</component>

</view>

=== wanggit/qcadoo-copy-framework/qcadoo-plugins-user-management/src/main/resources/qcadooUsers/view/groupDetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view"
	  xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd" name="groupDetails"
	  modelPlugin="qcadooSecurity" modelName="group" defaultAuthorizationRole="ROLE_GROUPS_VIEW">

	<component type="window" name="window">

		<ribbon>
			<group template="navigation"/>
			<group template="formSaveCopyAndRemoveActions" defaultAuthorizationRole="ROLE_GROUPS_EDIT"/>
			<group name="actions">
				<smallButton name="refresh" icon="updateIcon16.png" state="enabled" action="#{form}.performRefresh;" accesskey="r" />
			</group>
		</ribbon>

		<component type="form" name="group" reference="form" defaultAuthorizationRole="ROLE_GROUPS_EDIT">
			<component type="gridLayout" name="gridLayout" columns="3" rows="8">
				<layoutElement column="1" row="1">
					<component type="input" name="name" field="name" reference="name"/>
				</layoutElement>
				<layoutElement column="1" row="2">
					<component type="select" name="permissionType" field="permissionType"
					           reference="permissionType"/>
				</layoutElement>
				<layoutElement column="1" row="3" height="3">
					<component type="textarea" name="description" field="description" reference="description"/>
				</layoutElement>
				<layoutElement column="2" row="1" width="2" height="8">
					<component type="lookup" name="role" reference="roleLookup" field="roles" defaultVisible="false"
							   persistent="false" hasLabel="false">
						<option type="column" name="description" fields="identifier,description"
								expression="(#description == null) ? '@qcadooSecurity.role.' + #identifier + '.description' : #description" link="true"
								width="250"/>

						<option type="expression"
								value="'&lt;/b&gt; - ' + #identifier"/>

						<option type="fieldCode" value="identifier"/>
						<option type="multiselect" value="true"/>

						<option type="searchable" value="identifier"/>
						<option type="orderable" value="identifier"/>

						<criteriaModifier
								class="com.qcadoo.plugins.users.internal.GroupDetailsCriteriaModifiers"
								method="criteriaForGroups"/>
					</component>
					<component type="grid" name="groupComponents"
							   reference="groupComponents" source="#{form}.roles" defaultEnabled="false"
							   defaultAuthorizationRole="ROLE_GROUPS_EDIT">
						<option type="column" name="identifier" fields="identifier" width="50"/>
						<option type="column" name="description" fields="identifier,description"
								expression="(#description == null) ? '@qcadooSecurity.role.' + #identifier + '.description' : #description"/>

						<option type="order" column="identifier" direction="asc"/>

						<option type="searchable" value="identifier"/>
						<option type="orderable" value="identifier"/>

						<option type="paginable" value="false"/>
						<option type="multiselect" value="true"/>
						<option type="creatable" value="true"/>
						<option type="deletable" value="true"/>

						<option type="width" value="450"/>

						<option type="weakRelation" value="true"/>
						<option type="correspondingLookup" value="roleLookup"/>

						<option type="fullscreen" value="true"/>
						<option type="fixedHeight" value="true"/>
					</component>
				</layoutElement>
			</component>

			<option type="header" value="true"/>
			<option type="expression" value="(#identifier == null) ? #name : #identifier"/>
		</component>

	</component>

	<hooks>
		<beforeRender
				class="com.qcadoo.plugins.users.hooks.GroupDetailsHooks"
				method="fillCriteriaModifiers"/>
	</hooks>

</view>

=== wanggit/qcadoo-copy-framework/qcadoo-plugins-plugin-management/src/main/resources/qcadooPlugins/view/pluginsList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view" 
	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
	name="pluginsList"
	modelPlugin="qcadooPlugin"
	modelName="plugin"
	menuAccessible="true"
	defaultAuthorizationRole="ROLE_SUPERADMIN">
	
	<component type="window" name="window" reference="window">
		<ribbon>
			<group name="plugins">
				<bigButton name="downloadPlugin" icon="downloadIcon24.png"
					action="#{grid}.fireEvent(downloadPlugin);" message="qcadooPlugins.ribbon.messages.download" />
			</group>
			<group name="actions">
				<bigButton name="changeStatus" icon="enableIcon24.png"
					state="disabled">
					<script>
						<![CDATA[
							this.element.width(100);
							this.removeOnChangeListeners();
							this.addOnChangeListener({
								onClick: function() {
									if (this.state == "enable") {
										if (window.confirm("#{translate(qcadooPlugins.ribbon.confirms.enable)}")) {
											#{grid}.performEvent('enablePlugin', []);
										};
									} else if (this.state == "disable") {
										if (window.confirm("#{translate(qcadooPlugins.ribbon.confirms.disable)}")) {
											#{grid}.performEvent('disablePlugin', []);
										};
									}
								}
							});
						]]>
					</script>
				</bigButton>
				<smallButton name="remove" icon="deleteIcon16.png"
					state="disabled">
					<script>
						<![CDATA[
							this.removeOnChangeListeners();
							this.addOnChangeListener({
								onClick: function() {
									if (window.confirm("#{translate(qcadooPlugins.ribbon.confirms.remove)}")) {
										#{grid}.performEvent('removePlugin', []);
									}
								}
							});
						]]>
					</script>
				</smallButton>
			</group>
		</ribbon>
		<component type="grid" name="plugins" reference="grid">
			<option type="column" name="name" fields="name" link="true"
				width="100" />
			<option type="column" name="identifier" fields="identifier"
				link="true" width="80" />
			<option type="column" name="groupName" fields="groupName" width="100" />
			<option type="column" name="vendor" fields="vendor" width="100" />
			<option type="column" name="version" fields="version" width="40" />
			<option type="column" name="state" fields="state" width="60" />
			<option type="column" name="license" fields="license" width="60" />
			<option type="column" name="isSystem" fields="isSystem" width="60" />
			<option type="order" column="identifier" direction="asc" />
			<option type="correspondingView" value="qcadooPlugins/pluginDetails" />
			<option type="correspondingComponent" value="form" />
			<option type="correspondingViewInModal" value="true" />
			<option type="searchable" value="identifier,version,state,isSystem,groupName,license" />
			<option type="orderable" value="identifier,version,state,isSystem,groupName,license" />
			<option type="paginable" value="true" />
			<option type="deletable" value="false" />
			<option type="creatable" value="false" />
			<option type="fullscreen" value="true" />
			<option type="multiselect" value="true" />
			<listener event="downloadPlugin"
				class="com.qcadoo.plugins.plugins.internal.PluginManagmentViewHook"
				method="onDownloadButtonClick" />
			<listener event="enablePlugin"
				class="com.qcadoo.plugins.plugins.internal.PluginManagmentViewHook"
				method="onEnableButtonClick" />
			<listener event="disablePlugin"
				class="com.qcadoo.plugins.plugins.internal.PluginManagmentViewHook"
				method="onDisableButtonClick" />
			<listener event="removePlugin"
				class="com.qcadoo.plugins.plugins.internal.PluginManagmentViewHook"
				method="onRemoveButtonClick" />
			<script>
				<![CDATA[
					var downloadRibbonItem = #{window}.getRibbonItem("plugins.downloadPlugin");
					var changeStatusRibbonItem = #{window}.getRibbonItem("actions.changeStatus");
					var removeRibbonItem = #{window}.getRibbonItem("actions.remove");
					this.removeOnChangeListeners();
					this.addOnChangeListener({
						onChange: function(selectedEntitiesArray) {
							if (selectedEntitiesArray.length == 0) {
								changeStatusRibbonItem.disable();
								removeRibbonItem.disable();
							} else {
								var anySystem = false;
								var allEnabled = true;
								var noneEnabled = true;
								for (var i in selectedEntitiesArray) {
									if (selectedEntitiesArray[i].fields.isSystem == "1") {
										anySystem = true;
										break;
									}
									var state = selectedEntitiesArray[i].fields.state;
									if (state == 'ENABLED') {
										noneEnabled = false;
									} else {
										allEnabled = false;
									}
									
								}
								if (anySystem) {
									changeStatusRibbonItem.disable("#{translate(qcadooPlugins.ribbon.messages.base)}");
									removeRibbonItem.disable("#{translate(qcadooPlugins.ribbon.messages.base)}");
								} else {
									removeRibbonItem.enable("#{translate(qcadooPlugins.ribbon.messages.remove)}");
									if (allEnabled) {
										changeStatusRibbonItem.enable();
										changeStatusRibbonItem.state = "disable";
										changeStatusRibbonItem.setLabel("#{translate(qcadooPlugins.pluginsList.window.ribbon.actions.disable)}");
										changeStatusRibbonItem.setIcon('disableIcon24.png');
									} else if (noneEnabled) {
										changeStatusRibbonItem.enable();
										changeStatusRibbonItem.state = "enable";
										changeStatusRibbonItem.setLabel("#{translate(qcadooPlugins.pluginsList.window.ribbon.actions.changeStatus)}");
										changeStatusRibbonItem.setIcon('enableIcon24.png');
									} else {
										changeStatusRibbonItem.disable("#{translate(qcadooPlugins.ribbon.messages.mixedStatus)}");
									}
								}
							}
						}
					});
				]]>
			</script>
		</component>
		<option type="fixedHeight" value="true" />
		<option type="header" value="false" />
		<script>
			<![CDATA[
				this.addOnChangeListener({
					onSetValue: function(selectedEntitiesArray) {
						this.updateMenu();
					}
				});
			]]>
		</script>
	</component>
</view>
