=== wanggit/qcadoo-copy-framework/qcadoo-model/src/test/resources/com/qcadoo/model/modules/model.xsd
<?xml version="1.0"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.2.0

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://schema.qcadoo.org/modules/model" xmlns="http://schema.qcadoo.org/modules/model" 
	elementFormDefault="qualified">

	<xs:include schemaLocation="http://schema.qcadoo.org/common/model.xsd" />

	<xs:element name="model">
		<xs:complexType>
			<xs:attribute name="model" type="notEmptyString" use="required" />
			<xs:attribute name="resource" type="notEmptyString" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="model-field">
		<xs:complexType>	
			<xs:sequence>
				<xs:group ref="fieldsType" />
			</xs:sequence>
			<xs:attribute name="plugin" type="notEmptyString" use="required" />
			<xs:attribute name="model" type="notEmptyString" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="model-hook">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="hooksType" />
			</xs:sequence>
			<xs:attribute name="plugin" type="notEmptyString" use="required" />
			<xs:attribute name="model" type="notEmptyString" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="model-enum-value">
		<xs:complexType>
			<xs:attribute name="plugin" type="notEmptyString" use="required" />
			<xs:attribute name="model" type="notEmptyString" use="required" />
			<xs:attribute name="enum" type="notEmptyString" use="required" />
			<xs:attribute name="value" type="notEmptyString" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="dictionary">
		<xs:complexType>
			<xs:attribute name="name" type="notEmptyString" use="required" />
		</xs:complexType>
	</xs:element>

</xs:schema>

=== wanggit/qcadoo-copy-framework/qcadoo-model/src/test/resources/model/integration/plugin1/qcadoo-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.2.0

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<plugin plugin="products" group="framework" version="1.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/plugin"
	xmlns:model="http://schema.qcadoo.org/modules/model"
	xsi:schemaLocation="
		http://schema.qcadoo.org/plugin 
		http://schema.qcadoo.org/plugin.xsd 
		http://schema.qcadoo.org/modules/model 
		http://schema.qcadoo.org/modules/model.xsd">

	<information>
		<name>products</name>
	</information>

	<modules>
		<model:model model="product" resource="model/product.xml" />
		<model:model model="productListDto" resource="model/productListDto.xml" />
		<model:model model="component" resource="model/component.xml" />
		<model:model model="part" resource="model/part.xml" />
		
		<model:model model="factory" resource="model/factory.xml" />
		<model:model model="division" resource="model/division.xml" />

		<model:model model="versionableEntity" resource="model/versionableEntity.xml" />
	</modules>

</plugin>
